UKHomeOffice/dq-tf-apps

main.tf
Depends on gpdb repo branch: initial-gpdb, to pass tests.
gpdb repo branch: initial-gpdb needs to be merged. 
gpdb repo branch:
https://github.com/UKHomeOffice/dq-tf-gpdb/tree/initial-gpdb
=> internal, external_tableau, adding greenplum ip variable

main.tf, tests/apps_test.py
Change source for data feeds and data ingest modules.
=> module source update

main.tf, outputs.tf
Data Ingest
Data Feeds
Data Pipeline
GPDB
BDM
=> Route table variable

main.tf, tests/apps_test.py
Added public route table pointing to the IGW and subnet association for the public subnet.
=> Public route

tests/apps_test.py, variables.tf
=> Routetable

main.tf
=> feed in S3 bucket details for GP cluster backups

s3.tf
=> Fix KMS IAM policy to allow root access

main.tf
Make generic so the code can be reused easier.
=> Make generic

s3.tf, tests/apps_test.py
Add buckets for reference data and consolidated schedule pipelines
=> Feature ref data

main.tf, s3.tf, tests/apps_test.py
This is to add the FMS RDS instance
=> Feature fms

main.tf
These will need to be merged first:
https://github.com/UKHomeOffice/dq-tf-fms/pull/4
https://github.com/UKHomeOffice/dq-tf-external-tableau/pull/60
https://github.com/UKHomeOffice/dq-tf-datafeeds/pull/27
=> Add FMS, DRT and external feeds pipelines.

main.tf, tests/apps_test.py
This repo contains things that don't fit in a specific pipeline - mostly scripts and tools that we're using. The reason for adding it to apps is so that infra can create the reconciling lambda function and triggers.
=> Feature po

main.tf, outputs.tf
Reverts UKHomeOffice/dq-tf-apps#198
=> Revert "Remove rds"

main.tf
Modified value for dailytask source module
=> dailytask module path modified

variables.tf
Remove up to date API data access from BFID bastions
=> Remove up to date API data access from BFID bucket list

s3.tf, tests/apps_test.py
=> Add bfid virus scanned bucket

iam_crt.tf, tests/apps_test.py
=> Crt iam user

.drone.yml, ad_instance.tf, data.tf, iam_acl.tf, iam_airports.tf, iam_athena_cleanup.tf, iam_athena_maintenance_user.tf, iam_cloudwatch_user.tf, iam_crt.tf, iam_data_archive.tf, iam_nats.tf, iam_nats_historic_user.tf, iam_oag.tf, iam_pipeline_ops.tf, iam_rds_enhanced_monitoring.tf, iam_rds_maintenance.tf, iam_rmr.tf, main.tf, outputs.tf, s3.tf, tests/apps_test.py, variables.tf, versions.tf
What changes does this PR bring?
terraform 12 upgrade
What are the relevant tickets?
YEL-3182
Are tests included? (if applicable)
Infra is already plan and tested in TEST account
What if you don’t make a change?
terraform 12 has been out since 2 years ago. It has made change to HCL 2 and code support more functionalities with bug fixes.
=> Tf12 upgrade

iam_crt.tf
This is to create a randomized credentials which can be used programaticaly for CRT.
=> Crt user secrets

s3.tf, tests/apps_test.py, variables.tf
Reverts UKHomeOffice/dq-tf-apps#437
=> Revert "Feature/yel 5180 a"

.drone.yml, s3.tf
Apply intelligent tiering to S3 buckets within this repo.
Also, add in a vault token renew pipeline on a weekly cron
=> Cit 187 apply intelligent tiering
